image: go1.2
env:
  - GOPATH=/var/cache/drone
script:
  - go build main.go
  - ls -ltr
publish:
  s3:
    acl: public-read
    region: ap-northeast-1
    bucket: yosssi
    access_key: AKIAIFUQLLONKNLRFYOA
    secret_key: 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
    source: /var/cache/drone/src/github.com/yosssi/drone-test-publish/main
    target: latest/
